version: '2'
name: 'audioapp'
services:
  audio:
    build:
      context: ./pydocker
      dockerfile: Dockerfile
    image: audiodocker
    container_name: python_server
    ports:
      - "48080:48080"
    volumes:
      - ..:/app
    command: ./audioinfra/run_server.sh
  sql:
    build:
      context: .
    image: postgres:15.4
    container_name: sql_server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ..:/app