name: 'audioapp'
services:
  postgresql:
    build:
      context: .
    image: postgres:16.1
    container_name: sql_server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ..:/app
      - ./sqldocker/data:/var/lib/postgresql/data
  pgadmin:
    depends_on: [postgresql]
    build:
      context: .
    image: dpage/pgadmin4:8.0
    container_name: sql_gui
    environment:
      - PGADMIN_DEFAULT_EMAIL=boralek@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=boralek
    volumes:
      - ..:/app
    ports:
      - "5480:80"

