name: 'audioapp'
services:
  sql:
    build:
      context: .
    image: postgres:15.4
    container_name: sql_server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ..:/app
      - ./sqldocker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sqldocker/data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/root/.pgadmin
    depends_on:
      - sql
  audio:
    build:
      context: ./pydocker
      dockerfile: Dockerfile
    image: audiodocker
    container_name: python_server
    ports:
      - "48080:48080"
    depends_on:
      - sql
    volumes:
      - ..:/app
    command: ./audioinfra/run_server.sh
